# These are supported funding model platforms

github: devashishkatoriya # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://paypal.me/devashishkatoriya?locale.x=en_GB"]
